In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('IRIS.csv')

In [3]:
data.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [5]:
features = ['sepal_length','sepal_width','petal_length','petal_width']
prediction_class = ['species']

In [6]:
X = data[features].values

In [7]:
Y = data[prediction_class].values

In [8]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [9]:
Y

array([['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-se

In [10]:
type(X)

numpy.ndarray

In [11]:
type(Y)

numpy.ndarray

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.3)

In [14]:
x_train

array([[5.4, 3.9, 1.7, 0.4],
       [7.1, 3. , 5.9, 2.1],
       [5. , 3.5, 1.6, 0.6],
       [5.9, 3. , 5.1, 1.8],
       [5.3, 3.7, 1.5, 0.2],
       [5. , 3.4, 1.5, 0.2],
       [6.5, 3. , 5.2, 2. ],
       [5.2, 2.7, 3.9, 1.4],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.8, 3. , 1.4, 0.3],
       [7.2, 3.2, 6. , 1.8],
       [5. , 2.3, 3.3, 1. ],
       [5. , 3. , 1.6, 0.2],
       [5.6, 2.8, 4.9, 2. ],
       [5.5, 2.4, 3.8, 1.1],
       [5.1, 3.5, 1.4, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [6.4, 2.9, 4.3, 1.3],
       [7.2, 3.6, 6.1, 2.5],
       [5.7, 2.8, 4.1, 1.3],
       [5.1, 3.3, 1.7, 0.5],
       [5.6, 2.7, 4.2, 1.3],
       [6.4, 2.8, 5.6, 2.2],
       [6.7, 3.3, 5.7, 2.5],
       [7.6, 3. , 6.6, 2.1],
       [4.6, 3.1, 1.5, 0.2],
       [5.7, 2.6, 3.5, 1. ],
       [5.6, 3. , 4.1, 1.3],
       [6.2, 2.2, 4.5, 1.5],
       [5.8, 2.6, 4. , 1.2],
       [4.9, 3.1, 1.5, 0.1],
       [6. , 3. , 4.8, 1.8],
       [5.8, 2.7, 4.1, 1. ],
       [6.1, 2

In [15]:
x_test

array([[5.1, 3.8, 1.9, 0.4],
       [6.5, 3.2, 5.1, 2. ],
       [5.7, 3.8, 1.7, 0.3],
       [4.4, 3. , 1.3, 0.2],
       [6.5, 3. , 5.8, 2.2],
       [7.7, 3. , 6.1, 2.3],
       [6.4, 3.1, 5.5, 1.8],
       [5.8, 2.8, 5.1, 2.4],
       [5.9, 3. , 4.2, 1.5],
       [5.8, 4. , 1.2, 0.2],
       [4.4, 3.2, 1.3, 0.2],
       [6.4, 2.7, 5.3, 1.9],
       [5.1, 2.5, 3. , 1.1],
       [4.6, 3.4, 1.4, 0.3],
       [5.1, 3.5, 1.4, 0.3],
       [5. , 3.3, 1.4, 0.2],
       [6.7, 3. , 5.2, 2.3],
       [7.7, 2.8, 6.7, 2. ],
       [5.7, 4.4, 1.5, 0.4],
       [4.4, 2.9, 1.4, 0.2],
       [6.7, 3.1, 4.4, 1.4],
       [6.9, 3.1, 5.1, 2.3],
       [5.2, 3.4, 1.4, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 2.5, 4. , 1.3],
       [6.6, 3. , 4.4, 1.4],
       [6.1, 2.8, 4.7, 1.2],
       [6.3, 3.3, 4.7, 1.6],
       [7.4, 2.8, 6.1, 1.9],
       [5.5, 2.6, 4.4, 1.2],
       [4.7, 3.2, 1.3, 0.2],
       [5.7, 3. , 4.2, 1.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.7, 2.5, 5. , 2. ],
       [5.8, 2

In [16]:
y_train

array([['Iris-setosa'],
       ['Iris-virginica'],
       ['Iris-setosa'],
       ['Iris-virginica'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-virginica'],
       ['Iris-versicolor'],
       ['Iris-setosa'],
       ['Iris-versicolor'],
       ['Iris-setosa'],
       ['Iris-virginica'],
       ['Iris-versicolor'],
       ['Iris-setosa'],
       ['Iris-virginica'],
       ['Iris-versicolor'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-versicolor'],
       ['Iris-virginica'],
       ['Iris-versicolor'],
       ['Iris-setosa'],
       ['Iris-versicolor'],
       ['Iris-virginica'],
       ['Iris-virginica'],
       ['Iris-virginica'],
       ['Iris-setosa'],
       ['Iris-versicolor'],
       ['Iris-versicolor'],
       ['Iris-versicolor'],
       ['Iris-versicolor'],
       ['Iris-setosa'],
       ['Iris-virginica'],
       ['Iris-versicolor'],
       ['Iris-versicolor'],
       ['Iris-setosa'],
       ['Iris-versicolor'],
       ['Iris-virginica'],

In [17]:
y_test

array([['Iris-setosa'],
       ['Iris-virginica'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-virginica'],
       ['Iris-virginica'],
       ['Iris-virginica'],
       ['Iris-virginica'],
       ['Iris-versicolor'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-virginica'],
       ['Iris-versicolor'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-virginica'],
       ['Iris-virginica'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-versicolor'],
       ['Iris-virginica'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-versicolor'],
       ['Iris-versicolor'],
       ['Iris-versicolor'],
       ['Iris-versicolor'],
       ['Iris-virginica'],
       ['Iris-versicolor'],
       ['Iris-setosa'],
       ['Iris-versicolor'],
       ['Iris-setosa'],
       ['Iris-virginica'],
       ['Iris-virginica'],
       ['Iris-virginica'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris

In [18]:
from sklearn.ensemble import GradientBoostingClassifier

In [19]:
clf = GradientBoostingClassifier()

In [20]:
clf.fit(x_train, y_train)

/opt/anaconda3/envs/RP_env/lib/python3.11/site-packages/sklearn/ensemble/_gb.py:570: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GradientBoostingClassifier()

In [22]:
predictions = clf.predict(x_test)

In [23]:
predictions

array(['Iris-setosa', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-virginica', 'Iris-virginica', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-virginica', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-setosa'], dtype=object)

In [24]:
from sklearn.metrics import accuracy_score

In [27]:
print('The accuracy is: ', accuracy_score(y_test, predictions)*100)

The accuracy is:  97.77777777777777


In [36]:
y_test

array([['Iris-setosa'],
       ['Iris-virginica'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-virginica'],
       ['Iris-virginica'],
       ['Iris-virginica'],
       ['Iris-virginica'],
       ['Iris-versicolor'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-virginica'],
       ['Iris-versicolor'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-virginica'],
       ['Iris-virginica'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-versicolor'],
       ['Iris-virginica'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-versicolor'],
       ['Iris-versicolor'],
       ['Iris-versicolor'],
       ['Iris-versicolor'],
       ['Iris-virginica'],
       ['Iris-versicolor'],
       ['Iris-setosa'],
       ['Iris-versicolor'],
       ['Iris-setosa'],
       ['Iris-virginica'],
       ['Iris-virginica'],
       ['Iris-virginica'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris

In [29]:
new = pd.DataFrame()

In [30]:
new

Empty DataFrame
Columns: []
Index: []

In [38]:
new[['Actual Values']] = y_test
new['Predictions'] = predictions
new

Actual Values      Predictions
0       Iris-setosa      Iris-setosa
1    Iris-virginica   Iris-virginica
2       Iris-setosa      Iris-setosa
3       Iris-setosa      Iris-setosa
4    Iris-virginica   Iris-virginica
5    Iris-virginica   Iris-virginica
6    Iris-virginica   Iris-virginica
7    Iris-virginica   Iris-virginica
8   Iris-versicolor  Iris-versicolor
9       Iris-setosa      Iris-setosa
10      Iris-setosa      Iris-setosa
11   Iris-virginica   Iris-virginica
12  Iris-versicolor  Iris-versicolor
13      Iris-setosa      Iris-setosa
14      Iris-setosa      Iris-setosa
15      Iris-setosa      Iris-setosa
16   Iris-virginica   Iris-virginica
17   Iris-virginica   Iris-virginica
18      Iris-setosa      Iris-setosa
19      Iris-setosa      Iris-setosa
20  Iris-versicolor  Iris-versicolor
21   Iris-virginica   Iris-virginica
22      Iris-setosa      Iris-setosa
23      Iris-setosa      Iris-setosa
24  Iris-versicolor  Iris-versicolor
25  Iris-versicolor  Iris-versicolor
26  Iris-versicolor  Iris-versicolor
27  Iris-versicolor  Iris-versicolor
28   Iris-virginica   Iris-virginica
29  Iris-versicolor  Iris-versicolor
30      Iris-setosa      Iris-setosa
31  Iris-versicolor  Iris-versicolor
32      Iris-setosa      Iris-setosa
33   Iris-virginica   Iris-virginica
34   Iris-virginica   Iris-virginica
35   Iris-virginica   Iris-virginica
36      Iris-setosa      Iris-setosa
37      Iris-setosa      Iris-setosa
38      Iris-setosa      Iris-setosa
39  Iris-versicolor  Iris-versicolor
40   Iris-virginica   Iris-virginica
41      Iris-setosa      Iris-setosa
42  Iris-versicolor  Iris-versicolor
43  Iris-versicolor   Iris-virginica
44      Iris-setosa      Iris-setosa